host: "127.0.0.1"
port: 8000
data_directory: "./data"
postgres:
  db_schema: "ai-form-fill"
session_table_name: "agent_sessions"
data_table_name: "extracted_data"
use_extracted_data: false
extract_data: false
config_table_name: "agent_data"
tokenizer_llm_model: "gpt-5"
llm:
  model: "openrouter/nvidia/nemotron-3-nano-30b-a3b:free"
browser:
  headless: false
max_turns: 20
