#Use address ai-cc-db:5432 to access to this database from Adminer container. Use address localhost:5433 to access to this database from host machine.
services:

  ai-cc-db:
    build:
      context: ./postgres
    image: postgres-custom:1.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"